### PR TITLE
First change from fix-typo

### PR DESCRIPTION
**Pull request by SebCastroM**
please check the changes, i added a new line on post.html from a last created fix-typo branch

### CODE REVIEW

**Review by SebasCastro03 — CHANGES_REQUESTED** [review]
The changes from that brach have to be fix-typo changes, not to add lines of text, for that there is another branches

**Comment by SebCastroM** [comment]
Error fixed, changes done, there´s no addcional line, i erased it and do fix-typos (mainly accents in words título, párrafo and más)

**Review by SebasCastro03 — CHANGES_REQUESTED** [review]
Right, but still an error with the word titulo

**Review by SebasCastro03 — APPROVED** [review]
Ok, that´s allright, everything is ok

**Pull request merged**
